import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import LoaderPacman from '../components/LoaderPacman'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import { useState, CSSProperties } from "react";


const override: CSSProperties = {
  display: "block",
  margin: "0 auto",
  borderColor: "red",
};

// Simulere 2 sekunder lasting
export async function getStaticProps() {
  await new Promise((resolve) => setTimeout(resolve, 2000));
  return {
    props: {  }
  }
}


const Home: NextPage = () => {

  let [loading, setLoading] = useState(true);
  let [color, setColor] = useState("#666666");


  return (
    <div className={styles.container}>
      <Head>
        <title>Fold 4 Portofolio side</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} id="content">
        <Link href="/open">
          <Image src="/fold/closed.png" alt="Picture of a closed Samsung Fold4 with a case " width={100} height={600} />
        </Link>
      </main>

      <footer className={styles.footer}>
        <p>Portofolio side for Kristoffer S S</p>
      </footer>
    </div>
  )
}

export default Home
