import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Frontpage from '../components/Frontpage'
import LoaderPacman from '../components/LoaderPacman'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fold 4 Portofolio side</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoaderPacman />
        <Link href="/j">
        <Image src="/closed.png" alt="Picture of a closed Samsung Fold4 with a case " width={100} height={600} />

        </Link>
      </main>

      <footer className={styles.footer}>
<p>Portofolio side for Kristoffer S S</p>
      </footer>
    </div>
  )
}

export default Home
